spring:
  application:
    name: reactive-security-demo
#  r2dbc:
#    url: r2dbc:h2:mem:///testdb
#    username: sa
#    password:
#    pool:
#      enabled: true
#      initial-size: 10
#      max-size: 20
#      max-idle-time: 30m
#      max-acquire-time: 2s
#      validation-query: SELECT 1

jwt:
  secret: ${JWT_SECRET:mySecretKeyThatShouldBeAtLeast256BitsLongForHS256AlgorithmSecurityAndShouldBeStoredSecurely}
  expiration: 86400000 # 24 hours
  refresh-expiration: 604800000 # 7 days
  issuer: reactive-security-demo

server:
  port: 8080

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.netty.http.server: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
