CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username VARCHAR(50) UNIQUE NOT NULL,
  email VARCHAR(100) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL,
  roles VARCHAR(255),
  enabled BOOLEAN DEFAULT TRUE,
  account_non_expired BOOLEAN DEFAULT TRUE,
  account_non_locked BOOLEAN DEFAULT TRUE,
  credentials_non_expired BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMP,
  updated_at TIMESTAMP,
  last_login_at TIMESTAMP
);


MERGE INTO users (username, email, password, roles,
    enabled, account_non_expired, account_non_locked, credentials_non_expired)
    KEY(username)
    VALUES ('admin','admin@example.com',
    '{bcrypt}$2a$10$t93m62qD4RKlmudyRtpZPe6M6dYEImWxrf7iQnWokT7uDQoZuK7X2', -- "password"
    'ADMIN,USER', true, true, true, true);